CREATE TABLE TEST(
    ID NUMBER CHECK (ID <= 10000),
    USER_ID NUMBER,
    ROOM_ID NUMBER,
    CONSTRAINT TEST_ID PRIMARY KEY (ID, USER_ID,ROOM_ID),
    DATE_FROM TIMESTAMP,
    DATE_TO TIMESTAMP,
    MONEY_PAID FLOAT
);
